name: Add/Update Single File (manual)

on:
  workflow_dispatch:
    inputs:
      title:
        description: "PR title / commit message"
        required: true
        default: "Update via workflow"
      path:
        description: "Repository-relative path (e.g. js/format.js)"
        required: true
      content:
        description: "New file content (entire text; paste raw text, no code fences)"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set inputs to env (safe for multiline)
        env:
          IN_TITLE: ${{ inputs.title }}
          IN_PATH: ${{ inputs.path }}
          IN_CONTENT: ${{ inputs.content }}
        run: |
          echo "TITLE<<EOF" >> $GITHUB_ENV
          echo "$IN_TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "PATH_IN<<EOF" >> $GITHUB_ENV
          echo "$IN_PATH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "CONTENT<<EOF" >> $GITHUB_ENV
          echo "$IN_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create branch
        run: |
          set -e
          BR="auto/file-${{ github.run_id }}-$(date +%s)"
          echo "BR=$BR" >> $GITHUB_ENV
          git checkout -b "$BR"

      - name: Write file content
        run: |
          set -e
          mkdir -p "$(dirname "$PATH_IN")"
          # CONTENT は multiline を保持したまま書き込み
          printf "%s" "$CONTENT" > "$PATH_IN"
          # 改行を LF に正規化（CRLF混入対策）
          sed -i 's/\r$//' "$PATH_IN"
          echo "Wrote $PATH_IN:"
          head -n 50 "$PATH_IN" || true

      - name: Commit & push
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$PATH_IN"
          git status
          git commit -m "$TITLE"
          git push -u origin "$BR"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: ${{ env.TITLE }}
          body: |
            Applied via workflow_dispatch by ${{ github.actor }}.
            File: `${{ env.PATH_IN }}`
          branch: ${{ env.BR }}
          base: ${{ github.event.repository.default_branch }}
